### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by DanBuchan** [ractivejs/ractive-events-tap#17]
Your download links at 

https://ractivejs.github.io/ractive-events-tap/

are broken

**Comment by DanBuchan** [comment]
In fact http://www.ractivejs.org/plugins doesn't work either

**Comment by Madgvox** [comment]
An overhaul of the docs is definitely on our todo list. Thanks! :+1:

**Comment by DanBuchan** [comment]
Ha! Well I wasn't really suggesting a doc rewrite. Just a couple of link fixes. 

FYI, I'm very much enjoying using ractive so far.

**Comment by Madgvox** [comment]
Those broken links are indicative of the general state of disrepair the docs have fallen into. After 0.8 is released we're going to be doing some major reinvigorating of the docs.

**Comment by kit92** [comment]
Could we maybe just fix these two specific links? It's not hard to find the files on GitHub but the fact that it doesn't work as advertised is off putting for newcomers and having the on-tap event is something that's important.

**Comment by evs-chris** [comment]
Finally fixed :smile:
