### ISSUE TITLE
This plugin uses an experimental user-agent API

### ISSUE THREAD

**Issue by tearwyx** [ractivejs/ractive-events-tap#21]
**Chromium 54.0.2840.99 (64-bit)** says:

> Navigator.pointerEnabled is a non-standard API added for experiments only. It will be removed in near future.

**Comment by fskreuz** [comment]
This should be ok. The plugin is checking if the API exists before ever using it. Should it be removed, the code should just skip over.

- https://github.com/ractivejs/ractive-events-tap/blob/master/src/ractive-events-tap.js#L20
- https://github.com/ractivejs/ractive-events-tap/blob/master/src/ractive-events-tap.js#L22
- https://github.com/ractivejs/ractive-events-tap/blob/master/src/ractive-events-tap.js#L94
- https://github.com/ractivejs/ractive-events-tap/blob/master/src/ractive-events-tap.js#L98
