### ISSUE TITLE
Tap not working when parameter is set in Ractive 0.9.0

### ISSUE THREAD

**Issue by klickagent** [ractivejs/ractive-events-tap#22]
Hi,

Using the latest version of Ractive (0.9.0) this plugin is not working anymore when adding a parameter after the function name:
`on-tap="function:parameter"`

Can you please have a look into this? Thanks a lot!

Best regards,
Roman

**Comment by fskreuz** [comment]
I believe this syntax is already deprecated in 0.9 (it should have emitted a deprecation warning somewhere 0.8). The new syntax should be:

```
// Proxy event (name only, no args)
on-tap="function"

// Fire the event manually
on-tap="@this.fire('function', parameter1, parameter2, ...parameterN)"

// Method call
on-tap="@this.function(parameter1, parameter2, ...parameterN)"
```

**Comment by evs-chris** [comment]
To expand on that slightly, you can use `@` as shorthand for `@this` e.g. `@.fire('function', @context, parameter)`, and there's also a shorthand for proxy events `on-click="@this.fire('function', @context, parameter)"` -> `on-click="['function', parameter]"` if you don't mind shorthand.

**Comment by fskreuz** [comment]
Oooh! I didn't know about that second one. 😄

**Comment by evs-chris** [comment]
It's the expression-based compromise for the old proxy syntax 😄. Instance events are really awesome for many things, but they kinda got the short end of the stick when method and proxy syntax moved to expressions. Now the event directive will check for an array with a string first param as the only result of evaluating the event expression, and if that's what it finds, it will proxy the event for you without all the fluff around a `fire` call.

**Comment by klickagent** [comment]
Thanks a lot for your help! Works like charm!
